import { ArrowDownToLine, ArrowUpRight, BookOpen, CircleCheck, ExternalLink, GraduationCap, Network, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { engineeringProjects, futureDirections, humanMotorIntelligence, profile, researchProjects, researchStages, softwareResources } from "@/content/portfolio";
import { ResearchCard } from "@/components/ResearchCard";
import { StatusTag } from "@/components/StatusTag";
import { HeroDiagram, GeneralisationDiagram } from "@/components/Diagrams";
import { SEO } from "@/components/SEO";
import { JsonLd, personSchema, researchProjectSchema } from "@/components/JsonLd";

export default function Home() {
  return (
    <>
      <SEO title="Qussai Adlbi — Biomedical Engineering Researcher" description="Biomedical Engineering student researching reliable, zero-calibration, cross-subject decoding of human motor intent from sEMG, EEG, multimodal biosignals, and simulated systems." path="/" />
      <JsonLd data={personSchema} />
      <JsonLd data={researchProjectSchema} />
      <section className="home-hero" aria-labelledby="home-title">
        <aside className="hero-rail"><span>RESEARCH PROFILE</span><i /><p>Biomedical Engineering<br /><strong>Syria / Hungary</strong></p></aside>
        <div className="hero-copy-v3">
          <p className="eyebrow-v3"><i /> {profile.identity}</p>
          <h1 id="home-title">Decoding motor intent across people a model has <em>never seen.</em></h1>
          <p className="hero-statement">{profile.heroStatement}</p>
          <div className="hero-actions-v3"><Link href="/research" className="action-primary">Explore research <ArrowUpRight size={16} /></Link><a href={profile.cvDownload} download className="action-secondary">Download academic CV <ArrowDownToLine size={16} /></a></div>
          <p className="hero-footnote">Current focus: {profile.currentFocus}</p>
        </div>
        <figure className="hero-visual-v3"><HeroDiagram /><figcaption><span>biosignal → representation → unseen subject → motor intent</span><span>Conceptual framing</span></figcaption></figure>
      </section>

      <section className="credibility-strip" aria-label="Academic context"><span>Biomedical Engineering</span><span>Erasmus+ Academic Mobility</span><span>sEMG + EEG + BCI</span><span>Cross-Subject Research</span><span>Open Research Software</span></section>

      <section className="question-section-v3" aria-labelledby="question-title">
        <div className="section-index"><span>01</span><i /><span>THE PROBLEM</span></div>
        <div className="question-grid-v3"><div><p className="section-kicker-v3">Research question</p><h2 id="question-title">A model can look great on people it already knows, then fall apart on someone <em>new.</em></h2><blockquote>{profile.longQuestion}</blockquote></div><div className="question-note"><p>I work on getting motor intent out of a biosignal in a way that's measurable and reproducible. Model performance, generalisation, robustness, and clinical validation are four separate questions, and I test them separately.</p><Link href="/research" className="text-link-v3">Read the research programme <ExternalLink size={15} /></Link></div></div>
      </section>

      <section className="programme-section-v3" aria-labelledby="programme-title"><div className="programme-heading-v3"><div><p className="section-kicker-v3">Research programme</p><h2 id="programme-title">One question, several <em>experimental stages.</em></h2></div><p>Each stage narrows the claim from the one before it. The software exists to run these experiments — it's infrastructure, not the point of the exercise.</p></div><div className="programme-list-v3">{researchStages.map(([number, title, summary, evidence]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{summary}</p><small><CircleCheck size={14} /> {evidence}</small></article>)}</div></section>

      <section className="selected-section" aria-labelledby="selected-title"><div className="selected-header"><div><p className="section-kicker-v3">Selected research</p><h2 id="selected-title">Evidence in progress, not <em>inventory.</em></h2></div><Link href="/outputs" className="text-link-v3">Inspect all outputs <ArrowUpRight size={15} /></Link></div><div className="research-grid">{researchProjects.filter((project) => ["01", "02", "03"].includes(project.order)).map((project) => <ResearchCard project={project} key={project.slug} />)}</div><p className="selected-footnote">These three build on each other: first measure the metric honestly, then diagnose why the standard fix fails, then test whether a learned representation does better. A second track runs the same discipline on EEG, multimodal fusion, and simulated control. <Link href="/research" className="text-link-v3">See the full programme <ArrowUpRight size={13} /></Link>.</p></section>

      <section className="why-section"><figure><GeneralisationDiagram /><figcaption><span>the cross-subject question</span><span>Computational research, not a clinical claim</span></figcaption></figure><div><p className="section-kicker-v3">Why the work matters</p><h2>An average score is easy to get. A number you can <em>trust</em> is harder.</h2><p>You can't tell whether motor-intent decoding is actually reliable just by looking at a good average. So I start by questioning the metric itself, then dig into representation and domain shift, then test one narrow hypothesis at a time. That groundwork has to happen before any of this gets near a rehabilitation or assistive-device story.</p><div className="logic-chain"><span>MODEL PERFORMANCE</span><i>≠</i><span>GENERALISATION</span><i>≠</i><span>ROBUSTNESS</span><i>≠</i><span>CLINICAL VALIDATION</span></div></div></section>

      <section className="journey-section" aria-labelledby="journey-title"><div><p className="section-kicker-v3">International academic journey</p><h2 id="journey-title">A trajectory shaped across academic <em>environments.</em></h2></div><div className="journey-track"><article><span>01</span><h3>Biomedical Engineering</h3><p>Al-Andalus University for Medical Sciences<br />Tartus, Syria</p></article><article><span>02</span><h3>Erasmus+ Academic Mobility</h3><p>Pázmány Péter Catholic University<br />Budapest, Hungary</p></article><article><span>03</span><h3>Independent Research Programme</h3><p>Cross-subject biosignal learning and reproducible research infrastructure.</p></article><article><span>04</span><h3>European Graduate Research</h3><p>Next stage: deeper formal research training in biomedical AI, neurotechnology, or rehabilitation engineering.</p></article></div><p className="journey-boundary">It's a semester of academic mobility: real evidence that I can work in a different university system, not a language certificate and not a graduate degree.</p></section>

      <section className="infrastructure-section-v3" aria-labelledby="infrastructure-title"><div className="infrastructure-heading"><p className="section-kicker-v3 section-kicker-light">Human Motor Intelligence</p><h2 id="infrastructure-title">A research programme that keeps systems <em>independent and inspectable.</em></h2><p>{humanMotorIntelligence.description}</p><div className="infrastructure-boundary"><StatusTag status={humanMotorIntelligence.status} /><span>{humanMotorIntelligence.boundary}</span></div></div><div className="infrastructure-list">{softwareResources.slice(0, 4).map((resource, index) => <article key={resource.id}><span>{String(index + 1).padStart(2, "0")}</span><Network size={19} /><div><h3>{resource.title}</h3><small>{resource.role}</small></div><p>{resource.description}</p><StatusTag status={resource.status} /></article>)}</div><Link href="/systems" className="action-secondary action-secondary-light">Explore the systems map <ArrowUpRight size={16} /></Link><Link href="/outputs" className="action-secondary action-secondary-light">Inspect open research resources <ArrowUpRight size={16} /></Link></section>

      <section className="applied-section" aria-labelledby="applied-title"><div><p className="section-kicker-v3">Applied engineering practice</p><h2 id="applied-title">I design across <em>signal, system, and simulation.</em></h2><p>University engineering work and computational surgical-robotics research extend the same practice: define the system, state the evidence, and make the boundary visible.</p></div><div className="applied-list">{engineeringProjects.map((project, index) => <article key={project.title}><span>{String(index + 1).padStart(2, "0")}</span><div><small>{project.type} · {project.status}</small><h3>{project.title}</h3><p>{"homeSummary" in project ? project.homeSummary : project.description}</p><p className="applied-boundary"><b>Boundary</b>{project.boundary}</p></div></article>)}</div></section>

      <section className="future-section" aria-labelledby="future-title"><div><p className="section-kicker-v3">Current research directions</p><h2 id="future-title">Where the programme <em>currently extends.</em></h2></div><div className="future-list">{futureDirections.map(([title, text]) => <article key={title}><ShieldCheck size={19} /><h3>{title}</h3><p>{text}</p><small>Research direction</small></article>)}</div></section>

      <section className="readiness-section" aria-labelledby="readiness-title"><div className="readiness-heading"><p className="section-kicker-v3">Graduate and scholarship readiness</p><h2 id="readiness-title">Why graduate research, and why <em>now?</em></h2></div><div className="readiness-grid"><article><span>FOUNDATION</span><p>Biomedical engineering education and an emerging focus in biosignal research.</p></article><article><span>INITIATIVE</span><p>An independently developed programme organised around one methodological question.</p></article><article><span>EVIDENCE</span><p>Released research software, manuscript-stage work, and explicit evidence boundaries.</p></article><article><span>INTERNATIONAL READINESS</span><p>Erasmus+ academic mobility and experience of a different university environment.</p></article><article><span>CURRENT GAP</span><p>A need for deeper formal research training, advanced coursework, laboratory exposure, and thesis development.</p></article><article><span>NEXT STAGE</span><p>European graduate research as a logical bridge between current capability and responsible translational work.</p></article></div></section>

      <section className="home-about-cta"><div><GraduationCap size={23} /><p className="section-kicker-v3">About the researcher</p><h2>Early-career, but <em>already moving.</em></h2><p>I'm still an undergraduate. I'm not going to dress that up. What follows is a real account of a biomedical engineering student learning to ask one hard question properly and test it without cutting corners.</p></div><div><Link href="/about" className="text-link-v3">Read the academic journey <ArrowUpRight size={15} /></Link><Link href="/cv" className="text-link-v3">Read the full academic CV <BookOpen size={15} /></Link></div></section>

      <section className="home-contact-cta"><div><p className="section-kicker-v3">Get in touch</p><h2>Questions about the research?<br /><em>I'd like to hear them.</em></h2></div><div><a href={`mailto:${profile.email}`} className="action-primary">Email {profile.email} <ArrowUpRight size={16} /></a><a href={profile.cvDownload} download className="action-secondary">Download CV <ArrowDownToLine size={16} /></a></div></section>
    </>
  );
}
