import { ArrowLeft, ArrowUpRight, BookOpen, Code2, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";
import { profile, researchProjects } from "@/content/portfolio";
import { StatusTag } from "@/components/StatusTag";
import { SEO } from "@/components/SEO";
import { JsonLd, scholarlyArticleSchema } from "@/components/JsonLd";

function LinkIcon({ kind }: { kind: string }) { return kind === "repository" ? <Code2 size={15} /> : <BookOpen size={15} />; }

export default function ResearchDetail() {
  const [, params] = useRoute("/research/:slug");
  const project = researchProjects.find((item) => item.slug === params?.slug);
  if (!project) return <section className="page-hero"><p className="section-kicker-v3">Research</p><h1>That research record is not available.</h1><Link href="/research" className="action-secondary"><ArrowLeft size={16} /> Back to research</Link></section>;
  return <>
    <SEO title={project.title} description={project.question} path={`/research/${project.slug}`} />
    <JsonLd data={scholarlyArticleSchema({ title: project.title, description: project.question, status: project.status, slug: project.slug })} />
    <section className="detail-hero"><div><Link href="/research" className="back-link"><ArrowLeft size={15} /> Research index</Link><p className="section-kicker-v3">Research record {project.order}</p><StatusTag status={project.status} /><h1>{project.title}</h1><p>{project.question}</p></div><aside><span>WHAT</span><p>{project.shortTitle}</p><span>PART OF</span><p>{project.track === "core" ? "Core sEMG programme" : "EEG & multimodal extension"}</p><span>NEXT</span><p>{project.next}</p></aside></section><nav className="detail-nav" aria-label="Research detail navigation"><a href="#question">Question</a><a href="#protocol">Protocol</a><a href="#result">Observation</a><a href="#interpretation">Interpretation</a><a href="#contribution">Contribution</a><a href="#resources">Resources</a></nav><section className="detail-content"><article id="question"><span>01</span><div><h2>Research question</h2><p>{project.question}</p><h3>Background</h3><p>{project.background}</p></div></article><article id="protocol"><span>02</span><div><h2>Experimental protocol</h2><p>{project.method}</p><h3>Evaluation design</h3><p>{project.evaluation}</p></div></article><article id="result"><span>03</span><div><h2>Main observation</h2><p>{project.observation}</p></div></article><article id="interpretation"><span>04</span><div><h2>Interpretation</h2><p>{project.interpretation}</p>{project.statusBreakdown && <div className="hmi-status-grid" style={{ marginBottom: 20 }}><div><span className="hmi-status-label">Manuscript</span><p>{project.statusBreakdown.manuscript}</p></div><div><span className="hmi-status-label">Supervisory</span><p>{project.statusBreakdown.supervisory}</p></div><div><span className="hmi-status-label">Publication</span><p>{project.statusBreakdown.publication}</p></div></div>}<div className="boundary-box"><ShieldCheck size={19} /><div><h3>Scope of this result</h3><p>{project.limitation}</p></div></div></div></article><article id="contribution"><span>05</span><div><h2>My contribution</h2><ul>{project.contribution.map((item) => <li key={item}>{item}</li>)}</ul></div></article><article id="resources"><span>06</span><div><h2>Public resources</h2>{project.publicLinks.length ? <div className="detail-links">{project.publicLinks.map((link) => <a href={link.href} target="_blank" rel="noreferrer" key={link.href}><LinkIcon kind={link.kind} /> {link.label} <ArrowUpRight size={14} /></a>)}</div> : <p>This workstream does not yet have a public resource link; it is documented here at its current stage instead.</p>}</div></article></section><section className="detail-next"><p className="section-kicker-v3">Related research</p><h2>The programme moves by making the next question more <em>specific.</em></h2><Link href="/research" className="action-primary">Return to the research sequence <ArrowUpRight size={16} /></Link><a href={profile.cvDownload} className="action-secondary" download>Download Europass CV <ArrowUpRight size={16} /></a></section></>;
}
